<a href="https://colab.research.google.com/github/sourovcs/principal-component-analysis/blob/main/PCA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from numpy import array
from numpy import mean
from numpy import cov
from numpy.linalg import eig

In [ ]:
# dataset
D = array([[1, 0], [8, 0], [1, 4]])
print(D)

[[1 0]
 [8 0]
 [1 4]]


In [ ]:
print(D.T)

[[1 8 1]
 [0 0 4]]


In [ ]:
# calculating mean
M = mean(D.T, axis = 1)
print(M)

[3.33333333 1.33333333]


In [ ]:
A = D - M
print(A)

[[-2.33333333 -1.33333333]
 [ 4.66666667 -1.33333333]
 [-2.33333333  2.66666667]]


In [ ]:
# claculating covariance matrix
C = cov(A.T)
print(C)

[[16.33333333 -4.66666667]
 [-4.66666667  5.33333333]]


In [ ]:
eig_values, eig_vectors = eig(C)

In [ ]:
# print eigen values
print(eig_values)

[18.04636167  3.620305  ]


In [ ]:
# print eigen vectors
print(eig_vectors)

[[ 0.9387516   0.34459459]
 [-0.34459459  0.9387516 ]]


In [ ]:
pca = eig_vectors.T.dot(A.T)

In [ ]:
# print principle component
print(pca)

[[-1.73096095  4.84030026 -3.10933931]
 [-2.05572285  0.35643929  1.69928356]]
